export default {
  "currently": {
    "latitude": 35.241,
    "longitude": -97.501,
    "timezone": "America/Chicago",
    "offset": -5,
    "elevation": 1184,
    "currently": {
      "time": 1683170820,
      "summary": "Clear",
      "icon": "clear-night",
      "nearestStormDistance": 0,
      "nearestStormBearing": 0,
      "precipIntensity": 0,
      "precipProbability": 0,
      "precipIntensityError": 0,
      "precipType": "none",
      "temperature": 57.61,
      "apparentTemperature": 59.89,
      "dewPoint": 49.96,
      "humidity": 0.74,
      "pressure": 971.3,
      "windSpeed": 5.873,
      "windGust": 12.71,
      "windBearing": 162,
      "cloudCover": 0,
      "uvIndex": 0,
      "visibility": 10,
      "ozone": 326.19
    },
    "flags": {
      "sources": [
        "ETOPO1",
        "gfs",
        "gefs",
        "hrrrsubh",
        "hrrr"
      ],
      "sourceTimes": {
        "hrrr_0-18": "2023-05-04 01:00:00",
        "hrrr_subh": "2023-05-04 01:00:00",
        "hrrr_18-48": "2023-05-04 00:00:00",
        "gfs": "2023-05-03 18:00:00",
        "gefs": "2023-05-03 18:00:00"
      },
      "nearest-station": 0,
      "units": "us",
      "version": "V1.4.1"
    }
  },
  "today": {
    "latitude": 35.241,
    "longitude": -97.501,
    "timezone": "America/Chicago",
    "offset": -5,
    "elevation": 1184,
    "hourly": {
      "summary": "Cloudy",
      "icon": "cloudy",
      "data": [
        {
          "time": 1683090000,
          "icon": "clear-night",
          "summary": "Clear",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 57.83,
          "apparentTemperature": 58.87,
          "dewPoint": 47.14,
          "humidity": 0.63,
          "pressure": 973.5,
          "windSpeed": 1.5,
          "windGust": 8.38,
          "windBearing": 248.2,
          "cloudCover": 0,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 329.86
        },
        {
          "time": 1683093600,
          "icon": "clear-night",
          "summary": "Clear",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 56.82,
          "apparentTemperature": 57.67,
          "dewPoint": 46.69,
          "humidity": 0.63,
          "pressure": 974.1,
          "windSpeed": 2.47,
          "windGust": 8.66,
          "windBearing": 317.29,
          "cloudCover": 0,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 327.71
        },
        {
          "time": 1683097200,
          "icon": "clear-night",
          "summary": "Clear",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 55.69,
          "apparentTemperature": 56.05,
          "dewPoint": 45.46,
          "humidity": 0.61,
          "pressure": 974.6,
          "windSpeed": 1.69,
          "windGust": 7.68,
          "windBearing": 294.44,
          "cloudCover": 0.04,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 327.69
        },
        {
          "time": 1683100800,
          "icon": "clear-night",
          "summary": "Clear",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 54.57,
          "apparentTemperature": 54.49,
          "dewPoint": 44.33,
          "humidity": 0.62,
          "pressure": 974.7,
          "windSpeed": 4.85,
          "windGust": 12.99,
          "windBearing": 48.5,
          "cloudCover": 0,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 329.39
        },
        {
          "time": 1683104400,
          "icon": "clear-night",
          "summary": "Clear",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 53.22,
          "apparentTemperature": 52.35,
          "dewPoint": 42.19,
          "humidity": 0.61,
          "pressure": 974.4,
          "windSpeed": 6.03,
          "windGust": 13.4,
          "windBearing": 47.82,
          "cloudCover": 0.35,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 329.21
        },
        {
          "time": 1683108000,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 52.09,
          "apparentTemperature": 50.72,
          "dewPoint": 40.73,
          "humidity": 0.6,
          "pressure": 974.2,
          "windSpeed": 2,
          "windGust": 10.89,
          "windBearing": 77.91,
          "cloudCover": 1,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 330.48
        },
        {
          "time": 1683111600,
          "icon": "partly-cloudy-night",
          "summary": "Partly Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 51.31,
          "apparentTemperature": 50.16,
          "dewPoint": 41.41,
          "humidity": 0.63,
          "pressure": 974.9,
          "windSpeed": 2.81,
          "windGust": 6,
          "windBearing": 264.29,
          "cloudCover": 0.7,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 331.71
        },
        {
          "time": 1683115200,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 50.74,
          "apparentTemperature": 49.45,
          "dewPoint": 40.96,
          "humidity": 0.64,
          "pressure": 975.5,
          "windSpeed": 2.81,
          "windGust": 7.68,
          "windBearing": 5.71,
          "cloudCover": 1,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 332.32
        },
        {
          "time": 1683118800,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 54.12,
          "apparentTemperature": 52.86,
          "dewPoint": 41.07,
          "humidity": 0.61,
          "pressure": 975.6,
          "windSpeed": 2.75,
          "windGust": 9.63,
          "windBearing": 66.04,
          "cloudCover": 1,
          "uvIndex": 0.47,
          "visibility": 10,
          "ozone": 334.73
        },
        {
          "time": 1683122400,
          "icon": "partly-cloudy-day",
          "summary": "Partly Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 59.41,
          "apparentTemperature": 56.48,
          "dewPoint": 35.67,
          "humidity": 0.41,
          "pressure": 975.4,
          "windSpeed": 8.81,
          "windGust": 16.34,
          "windBearing": 92.73,
          "cloudCover": 0.58,
          "uvIndex": 1.28,
          "visibility": 10,
          "ozone": 334.93
        },
        {
          "time": 1683126000,
          "icon": "clear-day",
          "summary": "Clear",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 63.68,
          "apparentTemperature": 60.44,
          "dewPoint": 34.54,
          "humidity": 0.34,
          "pressure": 975.2,
          "windSpeed": 8.09,
          "windGust": 12.29,
          "windBearing": 111.25,
          "cloudCover": 0.34,
          "uvIndex": 1.84,
          "visibility": 10,
          "ozone": 336.12
        },
        {
          "time": 1683129600,
          "icon": "clear-day",
          "summary": "Clear",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 67.84,
          "apparentTemperature": 64.63,
          "dewPoint": 34.66,
          "humidity": 0.31,
          "pressure": 975.4,
          "windSpeed": 5.95,
          "windGust": 7.96,
          "windBearing": 129.29,
          "cloudCover": 0.14,
          "uvIndex": 3.66,
          "visibility": 10,
          "ozone": 337.8
        },
        {
          "time": 1683133200,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 71.67,
          "apparentTemperature": 67.68,
          "dewPoint": 31.62,
          "humidity": 0.24,
          "pressure": 974.8,
          "windSpeed": 6.12,
          "windGust": 7.4,
          "windBearing": 124.78,
          "cloudCover": 0.98,
          "uvIndex": 3.95,
          "visibility": 10,
          "ozone": 338.11
        },
        {
          "time": 1683136800,
          "icon": "partly-cloudy-day",
          "summary": "Partly Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 74.26,
          "apparentTemperature": 70.32,
          "dewPoint": 31.84,
          "humidity": 0.22,
          "pressure": 974.4,
          "windSpeed": 5.31,
          "windGust": 5.86,
          "windBearing": 178.49,
          "cloudCover": 0.72,
          "uvIndex": 1.17,
          "visibility": 10,
          "ozone": 338.87
        },
        {
          "time": 1683140400,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 75.83,
          "apparentTemperature": 72.06,
          "dewPoint": 32.52,
          "humidity": 0.22,
          "pressure": 973.6,
          "windSpeed": 3.21,
          "windGust": 6.42,
          "windBearing": 177.51,
          "cloudCover": 1,
          "uvIndex": 1.09,
          "visibility": 10,
          "ozone": 341.37
        },
        {
          "time": 1683144000,
          "icon": "partly-cloudy-day",
          "summary": "Partly Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 77.41,
          "apparentTemperature": 75.03,
          "dewPoint": 37.58,
          "humidity": 0.25,
          "pressure": 973.1,
          "windSpeed": 5.21,
          "windGust": 5.72,
          "windBearing": 249.62,
          "cloudCover": 0.75,
          "uvIndex": 0.85,
          "visibility": 10,
          "ozone": 341.3
        },
        {
          "time": 1683147600,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 69.42,
          "apparentTemperature": 72.28,
          "dewPoint": 51.19,
          "humidity": 0.54,
          "pressure": 972.9,
          "windSpeed": 6.52,
          "windGust": 7.96,
          "windBearing": 170.13,
          "cloudCover": 0.92,
          "uvIndex": 0.61,
          "visibility": 10,
          "ozone": 341.99
        },
        {
          "time": 1683151200,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.003,
          "precipProbability": 0.09,
          "precipIntensityError": 0.0082,
          "precipAccumulation": 0.003,
          "precipType": "rain",
          "temperature": 72.12,
          "apparentTemperature": 76.88,
          "dewPoint": 54.91,
          "humidity": 0.57,
          "pressure": 971.8,
          "windSpeed": 5.45,
          "windGust": 6.42,
          "windBearing": 181.47,
          "cloudCover": 1,
          "uvIndex": 0.36,
          "visibility": 10,
          "ozone": 338.03
        },
        {
          "time": 1683154800,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0032,
          "precipProbability": 0.1,
          "precipIntensityError": 0.0088,
          "precipAccumulation": 0.0032,
          "precipType": "rain",
          "temperature": 72.34,
          "apparentTemperature": 77.66,
          "dewPoint": 55.92,
          "humidity": 0.58,
          "pressure": 971.1,
          "windSpeed": 6.37,
          "windGust": 7.54,
          "windBearing": 164.74,
          "cloudCover": 0.93,
          "uvIndex": 0.28,
          "visibility": 10,
          "ozone": 335.3
        },
        {
          "time": 1683158400,
          "icon": "clear-day",
          "summary": "Clear",
          "precipIntensity": 0.0035,
          "precipProbability": 0.11,
          "precipIntensityError": 0.0095,
          "precipAccumulation": 0.0035,
          "precipType": "rain",
          "temperature": 71.89,
          "apparentTemperature": 77.15,
          "dewPoint": 55.81,
          "humidity": 0.58,
          "pressure": 971.4,
          "windSpeed": 5.39,
          "windGust": 6.84,
          "windBearing": 163.44,
          "cloudCover": 0,
          "uvIndex": 0.45,
          "visibility": 10,
          "ozone": 327.45
        },
        {
          "time": 1683162000,
          "icon": "clear-day",
          "summary": "Clear",
          "precipIntensity": 0.0024,
          "precipProbability": 0.08,
          "precipIntensityError": 0.0071,
          "precipAccumulation": 0.0024,
          "precipType": "rain",
          "temperature": 69.31,
          "apparentTemperature": 75.34,
          "dewPoint": 57.16,
          "humidity": 0.63,
          "pressure": 971.3,
          "windSpeed": 4.5,
          "windGust": 8.24,
          "windBearing": 150.26,
          "cloudCover": 0,
          "uvIndex": 0.25,
          "visibility": 10,
          "ozone": 325.93
        },
        {
          "time": 1683165600,
          "icon": "clear-night",
          "summary": "Clear",
          "precipIntensity": 0.0012,
          "precipProbability": 0.04,
          "precipIntensityError": 0.0048,
          "precipAccumulation": 0.0012,
          "precipType": "rain",
          "temperature": 65.82,
          "apparentTemperature": 72.45,
          "dewPoint": 58.17,
          "humidity": 0.72,
          "pressure": 970.7,
          "windSpeed": 5.44,
          "windGust": 10.61,
          "windBearing": 150.8,
          "cloudCover": 0.25,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 325.48
        },
        {
          "time": 1683169200,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 63.91,
          "apparentTemperature": 70.81,
          "dewPoint": 58.62,
          "humidity": 0.79,
          "pressure": 970.2,
          "windSpeed": 6.64,
          "windGust": 14.24,
          "windBearing": 157.75,
          "cloudCover": 1,
          "uvIndex": 0.03,
          "visibility": 10,
          "ozone": 322.96
        },
        {
          "time": 1683172800,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 62.44,
          "apparentTemperature": 70.2,
          "dewPoint": 59.97,
          "humidity": 0.88,
          "pressure": 970.9,
          "windSpeed": 6.81,
          "windGust": 15.22,
          "windBearing": 164.54,
          "cloudCover": 1,
          "uvIndex": 0,
          "visibility": 9.07,
          "ozone": 321.35
        },
        {
          "time": 1683176400,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 61.77,
          "apparentTemperature": 69.67,
          "dewPoint": 60.19,
          "humidity": 0.91,
          "pressure": 971.2,
          "windSpeed": 6.18,
          "windGust": 13.96,
          "windBearing": 151.7,
          "cloudCover": 1,
          "uvIndex": 0.06,
          "visibility": 8.33,
          "ozone": 319.53
        },
        {
          "time": 1683180000,
          "icon": "partly-cloudy-night",
          "summary": "Partly Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 62.67,
          "apparentTemperature": 70,
          "dewPoint": 59.29,
          "humidity": 0.85,
          "pressure": 971,
          "windSpeed": 6.93,
          "windGust": 14.24,
          "windBearing": 152.4,
          "cloudCover": 0.72,
          "uvIndex": 0,
          "visibility": 9.63,
          "ozone": 318.18
        },
        {
          "time": 1683183600,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0032,
          "precipProbability": 0.08,
          "precipIntensityError": 0.0045,
          "precipAccumulation": 0.0032,
          "precipType": "rain",
          "temperature": 62.56,
          "apparentTemperature": 69.19,
          "dewPoint": 58.17,
          "humidity": 0.83,
          "pressure": 970.9,
          "windSpeed": 11.35,
          "windGust": 18.43,
          "windBearing": 163.57,
          "cloudCover": 1,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 316.89
        },
        {
          "time": 1683187200,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.005,
          "precipProbability": 0.12,
          "precipIntensityError": 0.0074,
          "precipAccumulation": 0.005,
          "precipType": "rain",
          "temperature": 62.67,
          "apparentTemperature": 70.57,
          "dewPoint": 60.19,
          "humidity": 0.87,
          "pressure": 970.3,
          "windSpeed": 14.48,
          "windGust": 28.62,
          "windBearing": 173.35,
          "cloudCover": 1,
          "uvIndex": 0,
          "visibility": 1.86,
          "ozone": 315.09
        },
        {
          "time": 1683190800,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0068,
          "precipProbability": 0.17,
          "precipIntensityError": 0.0103,
          "precipAccumulation": 0.0068,
          "precipType": "rain",
          "temperature": 60.64,
          "apparentTemperature": 67.97,
          "dewPoint": 59.29,
          "humidity": 0.94,
          "pressure": 972.9,
          "windSpeed": 11.38,
          "windGust": 14.94,
          "windBearing": 173.66,
          "cloudCover": 1,
          "uvIndex": 0,
          "visibility": 1.55,
          "ozone": 315.51
        },
        {
          "time": 1683194400,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0066,
          "precipProbability": 0.24,
          "precipIntensityError": 0.0089,
          "precipAccumulation": 0.0066,
          "precipType": "rain",
          "temperature": 60.87,
          "apparentTemperature": 67.64,
          "dewPoint": 58.39,
          "humidity": 0.88,
          "pressure": 972.1,
          "windSpeed": 11.61,
          "windGust": 18.85,
          "windBearing": 161.78,
          "cloudCover": 1,
          "uvIndex": 0,
          "visibility": 3.29,
          "ozone": 315.98
        },
        {
          "time": 1683198000,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0064,
          "precipProbability": 0.31,
          "precipIntensityError": 0.0075,
          "precipAccumulation": 0.0064,
          "precipType": "rain",
          "temperature": 60.53,
          "apparentTemperature": 66.63,
          "dewPoint": 57.27,
          "humidity": 0.82,
          "pressure": 969.3,
          "windSpeed": 7.21,
          "windGust": 17.59,
          "windBearing": 137.35,
          "cloudCover": 0.99,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 314.91
        },
        {
          "time": 1683201600,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0062,
          "precipProbability": 0.38,
          "precipIntensityError": 0.0061,
          "precipAccumulation": 0.0062,
          "precipType": "rain",
          "temperature": 59.29,
          "apparentTemperature": 65.86,
          "dewPoint": 58.06,
          "humidity": 0.91,
          "pressure": 970.8,
          "windSpeed": 4.15,
          "windGust": 12.85,
          "windBearing": 132.27,
          "cloudCover": 0.87,
          "uvIndex": 0,
          "visibility": 8.39,
          "ozone": 315.95
        },
        {
          "time": 1683205200,
          "icon": "partly-cloudy-day",
          "summary": "Partly Cloudy",
          "precipIntensity": 0.0059,
          "precipProbability": 0.31,
          "precipIntensityError": 0.007,
          "precipAccumulation": 0.0059,
          "precipType": "rain",
          "temperature": 61.32,
          "apparentTemperature": 67.95,
          "dewPoint": 58.17,
          "humidity": 0.88,
          "pressure": 970.7,
          "windSpeed": 8.91,
          "windGust": 23.46,
          "windBearing": 166.4,
          "cloudCover": 0.44,
          "uvIndex": 0.53,
          "visibility": 9.38,
          "ozone": 315.91
        },
        {
          "time": 1683208800,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0056,
          "precipProbability": 0.24,
          "precipIntensityError": 0.0078,
          "precipAccumulation": 0.0056,
          "precipType": "rain",
          "temperature": 64.13,
          "apparentTemperature": 71.25,
          "dewPoint": 58.96,
          "humidity": 0.83,
          "pressure": 970.5,
          "windSpeed": 9.8,
          "windGust": 21.92,
          "windBearing": 184.09,
          "cloudCover": 1,
          "uvIndex": 1.72,
          "visibility": 10,
          "ozone": 317.1
        },
        {
          "time": 1683212400,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0053,
          "precipProbability": 0.16,
          "precipIntensityError": 0.0087,
          "precipAccumulation": 0.0053,
          "precipType": "rain",
          "temperature": 65.37,
          "apparentTemperature": 73.49,
          "dewPoint": 60.53,
          "humidity": 0.82,
          "pressure": 970.3,
          "windSpeed": 10.47,
          "windGust": 23.74,
          "windBearing": 193.11,
          "cloudCover": 1,
          "uvIndex": 3.19,
          "visibility": 10,
          "ozone": 317.85
        },
        {
          "time": 1683216000,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0058,
          "precipProbability": 0.22,
          "precipIntensityError": 0.0079,
          "precipAccumulation": 0.0058,
          "precipType": "rain",
          "temperature": 67.17,
          "apparentTemperature": 76.19,
          "dewPoint": 61.88,
          "humidity": 0.83,
          "pressure": 970.7,
          "windSpeed": 10.51,
          "windGust": 23.74,
          "windBearing": 196.99,
          "cloudCover": 1,
          "uvIndex": 4.69,
          "visibility": 10,
          "ozone": 319.82
        },
        {
          "time": 1683219600,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0063,
          "precipProbability": 0.28,
          "precipIntensityError": 0.0072,
          "precipAccumulation": 0.0063,
          "precipType": "rain",
          "temperature": 66.83,
          "apparentTemperature": 76.71,
          "dewPoint": 63.12,
          "humidity": 0.85,
          "pressure": 970.7,
          "windSpeed": 7,
          "windGust": 20.94,
          "windBearing": 184.57,
          "cloudCover": 1,
          "uvIndex": 6.12,
          "visibility": 10,
          "ozone": 319.32
        },
        {
          "time": 1683223200,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0068,
          "precipProbability": 0.34,
          "precipIntensityError": 0.0065,
          "precipAccumulation": 0.0068,
          "precipType": "rain",
          "temperature": 70.54,
          "apparentTemperature": 82.25,
          "dewPoint": 65.59,
          "humidity": 0.81,
          "pressure": 970.2,
          "windSpeed": 7.08,
          "windGust": 19.13,
          "windBearing": 194.86,
          "cloudCover": 1,
          "uvIndex": 5.31,
          "visibility": 10,
          "ozone": 322.4
        },
        {
          "time": 1683226800,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0093,
          "precipProbability": 0.33,
          "precipIntensityError": 0.0124,
          "precipAccumulation": 0.0093,
          "precipType": "rain",
          "temperature": 74.14,
          "apparentTemperature": 87.09,
          "dewPoint": 67.17,
          "humidity": 0.76,
          "pressure": 969.5,
          "windSpeed": 8.12,
          "windGust": 15.22,
          "windBearing": 199.06,
          "cloudCover": 1,
          "uvIndex": 3.72,
          "visibility": 10,
          "ozone": 323.96
        },
        {
          "time": 1683230400,
          "icon": "rain",
          "summary": "Rain",
          "precipIntensity": 0.0118,
          "precipProbability": 0.31,
          "precipIntensityError": 0.0184,
          "precipAccumulation": 0.0118,
          "precipType": "rain",
          "temperature": 72.91,
          "apparentTemperature": 85.85,
          "dewPoint": 67.17,
          "humidity": 0.82,
          "pressure": 968.5,
          "windSpeed": 5.01,
          "windGust": 10.33,
          "windBearing": 157.01,
          "cloudCover": 1,
          "uvIndex": 2.71,
          "visibility": 10,
          "ozone": 323.17
        },
        {
          "time": 1683234000,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0143,
          "precipProbability": 0.29,
          "precipIntensityError": 0.0244,
          "precipAccumulation": 0.0143,
          "precipType": "rain",
          "temperature": 73.47,
          "apparentTemperature": 86.51,
          "dewPoint": 67.28,
          "humidity": 0.82,
          "pressure": 967.8,
          "windSpeed": 9.3,
          "windGust": 16.76,
          "windBearing": 147.26,
          "cloudCover": 1,
          "uvIndex": 1.57,
          "visibility": 10,
          "ozone": 323.24
        },
        {
          "time": 1683237600,
          "icon": "rain",
          "summary": "Rain",
          "precipIntensity": 0.0225,
          "precipProbability": 0.43,
          "precipIntensityError": 0.0317,
          "precipAccumulation": 0.0225,
          "precipType": "rain",
          "temperature": 74.82,
          "apparentTemperature": 89.07,
          "dewPoint": 68.74,
          "humidity": 0.82,
          "pressure": 967.6,
          "windSpeed": 10.68,
          "windGust": 18.29,
          "windBearing": 152.76,
          "cloudCover": 1,
          "uvIndex": 4.13,
          "visibility": 10,
          "ozone": 322.35
        },
        {
          "time": 1683241200,
          "icon": "rain",
          "summary": "Rain",
          "precipIntensity": 0.0307,
          "precipProbability": 0.56,
          "precipIntensityError": 0.0391,
          "precipAccumulation": 0.0307,
          "precipType": "rain",
          "temperature": 72.68,
          "apparentTemperature": 86.18,
          "dewPoint": 67.84,
          "humidity": 0.82,
          "pressure": 966.9,
          "windSpeed": 10.17,
          "windGust": 23.74,
          "windBearing": 136.67,
          "cloudCover": 1,
          "uvIndex": 3.02,
          "visibility": 10,
          "ozone": 320.69
        },
        {
          "time": 1683244800,
          "icon": "rain",
          "summary": "Rain",
          "precipIntensity": 0.0389,
          "precipProbability": 0.7,
          "precipIntensityError": 0.0465,
          "precipAccumulation": 0.0389,
          "precipType": "rain",
          "temperature": 67.22,
          "apparentTemperature": 77.77,
          "dewPoint": 64.05,
          "humidity": 0.9,
          "pressure": 964.19,
          "windSpeed": 19.2,
          "windGust": 31.04,
          "windBearing": 154.86,
          "cloudCover": 0.76,
          "uvIndex": 0.62,
          "visibility": 9.32,
          "ozone": 322.22
        },
        {
          "time": 1683248400,
          "icon": "rain",
          "summary": "Rain",
          "precipIntensity": 0.0309,
          "precipProbability": 0.54,
          "precipIntensityError": 0.0413,
          "precipAccumulation": 0.0309,
          "precipType": "rain",
          "temperature": 66.71,
          "apparentTemperature": 76.52,
          "dewPoint": 63.01,
          "humidity": 0.88,
          "pressure": 963.56,
          "windSpeed": 21.57,
          "windGust": 33.52,
          "windBearing": 147.75,
          "cloudCover": 0.16,
          "uvIndex": 0.43,
          "visibility": 10,
          "ozone": 323.17
        },
        {
          "time": 1683252000,
          "icon": "rain",
          "summary": "Rain",
          "precipIntensity": 0.0229,
          "precipProbability": 0.39,
          "precipIntensityError": 0.0361,
          "precipAccumulation": 0.0229,
          "precipType": "rain",
          "temperature": 65.25,
          "apparentTemperature": 74.74,
          "dewPoint": 62.56,
          "humidity": 0.91,
          "pressure": 963.38,
          "windSpeed": 18.59,
          "windGust": 34.91,
          "windBearing": 150.43,
          "cloudCover": 0,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 321.7
        },
        {
          "time": 1683255600,
          "icon": "clear-night",
          "summary": "Clear",
          "precipIntensity": 0.0148,
          "precipProbability": 0.24,
          "precipIntensityError": 0.0309,
          "precipAccumulation": 0.0148,
          "precipType": "rain",
          "temperature": 64.16,
          "apparentTemperature": 73.66,
          "dewPoint": 62.57,
          "humidity": 0.94,
          "pressure": 963.77,
          "windSpeed": 18.08,
          "windGust": 38.79,
          "windBearing": 155.97,
          "cloudCover": 0.04,
          "uvIndex": 0.03,
          "visibility": 10,
          "ozone": 321.2
        },
        {
          "time": 1683259200,
          "icon": "clear-night",
          "summary": "Clear",
          "precipIntensity": 0.0099,
          "precipProbability": 0.24,
          "precipIntensityError": 0.0206,
          "precipAccumulation": 0.0099,
          "precipType": "rain",
          "temperature": 65.7,
          "apparentTemperature": 76.07,
          "dewPoint": 63.79,
          "humidity": 0.93,
          "pressure": 963.29,
          "windSpeed": 20.47,
          "windGust": 41.7,
          "windBearing": 165.52,
          "cloudCover": 0,
          "uvIndex": 0.03,
          "visibility": 10,
          "ozone": 320.46
        }
      ]
    },
    "flags": {
      "sources": [
        "ETOPO1",
        "gfs",
        "gefs",
        "hrrrsubh",
        "hrrr"
      ],
      "sourceTimes": {
        "hrrr_0-18": "2023-05-03 03:00:00",
        "hrrr_subh": "2023-05-03 03:00:00",
        "hrrr_18-48": "2023-05-03 00:00:00",
        "gfs": "2023-05-02 18:00:00",
        "gefs": "2023-05-02 18:00:00"
      },
      "nearest-station": 0,
      "units": "us",
      "version": "V1.4.1"
    }
  },
  "yesterday": {
    "latitude": 35.241,
    "longitude": -97.501,
    "timezone": "America/Chicago",
    "offset": -5,
    "elevation": 1184,
    "hourly": {
      "summary": "Cloudy",
      "icon": "cloudy",
      "data": [
        {
          "time": 1683082800,
          "icon": "clear-night",
          "summary": "Clear",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 63.12,
          "apparentTemperature": 63.3,
          "dewPoint": 45.01,
          "humidity": 0.48,
          "pressure": 972.8,
          "windSpeed": 5.69,
          "windGust": 10.19,
          "windBearing": 24.68,
          "cloudCover": 0.21,
          "uvIndex": 0.03,
          "visibility": 10,
          "ozone": 330.25
        },
        {
          "time": 1683086400,
          "icon": "partly-cloudy-night",
          "summary": "Partly Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 60.98,
          "apparentTemperature": 61.79,
          "dewPoint": 46.58,
          "humidity": 0.55,
          "pressure": 973.3,
          "windSpeed": 4.58,
          "windGust": 11.03,
          "windBearing": 37.57,
          "cloudCover": 0.41,
          "uvIndex": 0.03,
          "visibility": 10,
          "ozone": 329.63
        },
        {
          "time": 1683090000,
          "icon": "clear-night",
          "summary": "Clear",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 59.18,
          "apparentTemperature": 60.13,
          "dewPoint": 46.92,
          "humidity": 0.59,
          "pressure": 973.8,
          "windSpeed": 4.58,
          "windGust": 12.43,
          "windBearing": 52.43,
          "cloudCover": 0,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 329.86
        },
        {
          "time": 1683093600,
          "icon": "clear-night",
          "summary": "Clear",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 57.49,
          "apparentTemperature": 58.77,
          "dewPoint": 47.71,
          "humidity": 0.64,
          "pressure": 974.3,
          "windSpeed": 1.38,
          "windGust": 11.59,
          "windBearing": 336.04,
          "cloudCover": 0,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 327.71
        },
        {
          "time": 1683097200,
          "icon": "partly-cloudy-night",
          "summary": "Partly Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 56.26,
          "apparentTemperature": 57.16,
          "dewPoint": 46.81,
          "humidity": 0.65,
          "pressure": 974.1,
          "windSpeed": 2.3,
          "windGust": 12.99,
          "windBearing": 345.96,
          "cloudCover": 0.44,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 327.69
        },
        {
          "time": 1683100800,
          "icon": "partly-cloudy-night",
          "summary": "Partly Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 56.26,
          "apparentTemperature": 55.92,
          "dewPoint": 43.66,
          "humidity": 0.58,
          "pressure": 974.3,
          "windSpeed": 4.58,
          "windGust": 14.8,
          "windBearing": 52.43,
          "cloudCover": 0.4,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 329.39
        },
        {
          "time": 1683104400,
          "icon": "clear-night",
          "summary": "Clear",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 54.57,
          "apparentTemperature": 54.11,
          "dewPoint": 43.32,
          "humidity": 0.6,
          "pressure": 974.2,
          "windSpeed": 1.29,
          "windGust": 12.01,
          "windBearing": 77.47,
          "cloudCover": 0,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 329.21
        },
        {
          "time": 1683108000,
          "icon": "clear-night",
          "summary": "Clear",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 54.12,
          "apparentTemperature": 52.94,
          "dewPoint": 41.29,
          "humidity": 0.55,
          "pressure": 974.4,
          "windSpeed": 1.9,
          "windGust": 10.75,
          "windBearing": 126.03,
          "cloudCover": 0.04,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 330.48
        },
        {
          "time": 1683111600,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 52.88,
          "apparentTemperature": 50.34,
          "dewPoint": 37.02,
          "humidity": 0.49,
          "pressure": 974.1,
          "windSpeed": 4.18,
          "windGust": 12.99,
          "windBearing": 64.29,
          "cloudCover": 1,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 331.71
        },
        {
          "time": 1683115200,
          "icon": "partly-cloudy-day",
          "summary": "Partly Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 52.09,
          "apparentTemperature": 49.86,
          "dewPoint": 38.03,
          "humidity": 0.54,
          "pressure": 974.7,
          "windSpeed": 4.75,
          "windGust": 10.47,
          "windBearing": 28.07,
          "cloudCover": 0.44,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 332.32
        },
        {
          "time": 1683118800,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 55.13,
          "apparentTemperature": 52.93,
          "dewPoint": 38.14,
          "humidity": 0.51,
          "pressure": 974.8,
          "windSpeed": 3.53,
          "windGust": 10.75,
          "windBearing": 71.57,
          "cloudCover": 0.88,
          "uvIndex": 0.47,
          "visibility": 10,
          "ozone": 334.73
        },
        {
          "time": 1683122400,
          "icon": "partly-cloudy-day",
          "summary": "Partly Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 61.09,
          "apparentTemperature": 58.04,
          "dewPoint": 35.22,
          "humidity": 0.37,
          "pressure": 974.9,
          "windSpeed": 7.73,
          "windGust": 14.94,
          "windBearing": 106.8,
          "cloudCover": 0.73,
          "uvIndex": 1.28,
          "visibility": 10,
          "ozone": 334.93
        },
        {
          "time": 1683126000,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 65.03,
          "apparentTemperature": 62.9,
          "dewPoint": 38.37,
          "humidity": 0.38,
          "pressure": 975.4,
          "windSpeed": 7.4,
          "windGust": 12.01,
          "windBearing": 148.11,
          "cloudCover": 1,
          "uvIndex": 1.84,
          "visibility": 10,
          "ozone": 336.12
        },
        {
          "time": 1683129600,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 66.04,
          "apparentTemperature": 63.81,
          "dewPoint": 38.03,
          "humidity": 0.36,
          "pressure": 976.3,
          "windSpeed": 5.56,
          "windGust": 9.08,
          "windBearing": 191.59,
          "cloudCover": 0.92,
          "uvIndex": 3.66,
          "visibility": 10,
          "ozone": 337.8
        },
        {
          "time": 1683133200,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 61.54,
          "apparentTemperature": 62.31,
          "dewPoint": 46.47,
          "humidity": 0.59,
          "pressure": 976.4,
          "windSpeed": 8.92,
          "windGust": 10.33,
          "windBearing": 230.08,
          "cloudCover": 0.97,
          "uvIndex": 3.95,
          "visibility": 4.1,
          "ozone": 338.11
        },
        {
          "time": 1683136800,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 62.89,
          "apparentTemperature": 64.13,
          "dewPoint": 47.59,
          "humidity": 0.58,
          "pressure": 975.3,
          "windSpeed": 3.24,
          "windGust": 7.12,
          "windBearing": 82.57,
          "cloudCover": 1,
          "uvIndex": 1.17,
          "visibility": 10,
          "ozone": 338.87
        },
        {
          "time": 1683140400,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 63.68,
          "apparentTemperature": 65.91,
          "dewPoint": 49.84,
          "humidity": 0.64,
          "pressure": 974.9,
          "windSpeed": 9.32,
          "windGust": 11.31,
          "windBearing": 209.64,
          "cloudCover": 1,
          "uvIndex": 1.09,
          "visibility": 10,
          "ozone": 341.37
        },
        {
          "time": 1683144000,
          "icon": "partly-cloudy-day",
          "summary": "Partly Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 67.06,
          "apparentTemperature": 69.34,
          "dewPoint": 49.96,
          "humidity": 0.57,
          "pressure": 974,
          "windSpeed": 7.37,
          "windGust": 9.77,
          "windBearing": 155.38,
          "cloudCover": 0.68,
          "uvIndex": 0.85,
          "visibility": 10,
          "ozone": 341.3
        },
        {
          "time": 1683147600,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 69.42,
          "apparentTemperature": 72.28,
          "dewPoint": 51.19,
          "humidity": 0.54,
          "pressure": 972.9,
          "windSpeed": 6.52,
          "windGust": 7.96,
          "windBearing": 170.13,
          "cloudCover": 0.92,
          "uvIndex": 0.61,
          "visibility": 10,
          "ozone": 341.99
        },
        {
          "time": 1683151200,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.003,
          "precipProbability": 0.09,
          "precipIntensityError": 0.0082,
          "precipAccumulation": 0.003,
          "precipType": "rain",
          "temperature": 72.12,
          "apparentTemperature": 76.88,
          "dewPoint": 54.91,
          "humidity": 0.57,
          "pressure": 971.8,
          "windSpeed": 5.45,
          "windGust": 6.42,
          "windBearing": 181.47,
          "cloudCover": 1,
          "uvIndex": 0.36,
          "visibility": 10,
          "ozone": 338.03
        },
        {
          "time": 1683154800,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0032,
          "precipProbability": 0.1,
          "precipIntensityError": 0.0088,
          "precipAccumulation": 0.0032,
          "precipType": "rain",
          "temperature": 72.34,
          "apparentTemperature": 77.66,
          "dewPoint": 55.92,
          "humidity": 0.58,
          "pressure": 971.1,
          "windSpeed": 6.37,
          "windGust": 7.54,
          "windBearing": 164.74,
          "cloudCover": 0.93,
          "uvIndex": 0.28,
          "visibility": 10,
          "ozone": 335.3
        },
        {
          "time": 1683158400,
          "icon": "clear-day",
          "summary": "Clear",
          "precipIntensity": 0.0035,
          "precipProbability": 0.11,
          "precipIntensityError": 0.0095,
          "precipAccumulation": 0.0035,
          "precipType": "rain",
          "temperature": 71.89,
          "apparentTemperature": 77.15,
          "dewPoint": 55.81,
          "humidity": 0.58,
          "pressure": 971.4,
          "windSpeed": 5.39,
          "windGust": 6.84,
          "windBearing": 163.44,
          "cloudCover": 0,
          "uvIndex": 0.45,
          "visibility": 10,
          "ozone": 327.45
        },
        {
          "time": 1683162000,
          "icon": "clear-day",
          "summary": "Clear",
          "precipIntensity": 0.0024,
          "precipProbability": 0.08,
          "precipIntensityError": 0.0071,
          "precipAccumulation": 0.0024,
          "precipType": "rain",
          "temperature": 69.31,
          "apparentTemperature": 75.34,
          "dewPoint": 57.16,
          "humidity": 0.63,
          "pressure": 971.3,
          "windSpeed": 4.5,
          "windGust": 8.24,
          "windBearing": 150.26,
          "cloudCover": 0,
          "uvIndex": 0.25,
          "visibility": 10,
          "ozone": 325.93
        },
        {
          "time": 1683165600,
          "icon": "clear-night",
          "summary": "Clear",
          "precipIntensity": 0.0012,
          "precipProbability": 0.04,
          "precipIntensityError": 0.0048,
          "precipAccumulation": 0.0012,
          "precipType": "rain",
          "temperature": 65.82,
          "apparentTemperature": 72.45,
          "dewPoint": 58.17,
          "humidity": 0.72,
          "pressure": 970.7,
          "windSpeed": 5.44,
          "windGust": 10.61,
          "windBearing": 150.8,
          "cloudCover": 0.25,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 325.48
        },
        {
          "time": 1683169200,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 63.91,
          "apparentTemperature": 70.81,
          "dewPoint": 58.62,
          "humidity": 0.79,
          "pressure": 970.2,
          "windSpeed": 6.64,
          "windGust": 14.24,
          "windBearing": 157.75,
          "cloudCover": 1,
          "uvIndex": 0.03,
          "visibility": 10,
          "ozone": 322.96
        },
        {
          "time": 1683172800,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 62.44,
          "apparentTemperature": 70.2,
          "dewPoint": 59.97,
          "humidity": 0.88,
          "pressure": 970.9,
          "windSpeed": 6.81,
          "windGust": 15.22,
          "windBearing": 164.54,
          "cloudCover": 1,
          "uvIndex": 0,
          "visibility": 9.07,
          "ozone": 321.35
        },
        {
          "time": 1683176400,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 61.77,
          "apparentTemperature": 69.67,
          "dewPoint": 60.19,
          "humidity": 0.91,
          "pressure": 971.2,
          "windSpeed": 6.18,
          "windGust": 13.96,
          "windBearing": 151.7,
          "cloudCover": 1,
          "uvIndex": 0.06,
          "visibility": 8.33,
          "ozone": 319.53
        },
        {
          "time": 1683180000,
          "icon": "partly-cloudy-night",
          "summary": "Partly Cloudy",
          "precipIntensity": 0,
          "precipProbability": 0,
          "precipIntensityError": 0,
          "precipAccumulation": 0,
          "precipType": "none",
          "temperature": 62.67,
          "apparentTemperature": 70,
          "dewPoint": 59.29,
          "humidity": 0.85,
          "pressure": 971,
          "windSpeed": 6.93,
          "windGust": 14.24,
          "windBearing": 152.4,
          "cloudCover": 0.72,
          "uvIndex": 0,
          "visibility": 9.63,
          "ozone": 318.18
        },
        {
          "time": 1683183600,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0032,
          "precipProbability": 0.08,
          "precipIntensityError": 0.0045,
          "precipAccumulation": 0.0032,
          "precipType": "rain",
          "temperature": 62.56,
          "apparentTemperature": 69.19,
          "dewPoint": 58.17,
          "humidity": 0.83,
          "pressure": 970.9,
          "windSpeed": 11.35,
          "windGust": 18.43,
          "windBearing": 163.57,
          "cloudCover": 1,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 316.89
        },
        {
          "time": 1683187200,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.005,
          "precipProbability": 0.12,
          "precipIntensityError": 0.0074,
          "precipAccumulation": 0.005,
          "precipType": "rain",
          "temperature": 62.67,
          "apparentTemperature": 70.57,
          "dewPoint": 60.19,
          "humidity": 0.87,
          "pressure": 970.3,
          "windSpeed": 14.48,
          "windGust": 28.62,
          "windBearing": 173.35,
          "cloudCover": 1,
          "uvIndex": 0,
          "visibility": 1.86,
          "ozone": 315.09
        },
        {
          "time": 1683190800,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0068,
          "precipProbability": 0.17,
          "precipIntensityError": 0.0103,
          "precipAccumulation": 0.0068,
          "precipType": "rain",
          "temperature": 60.64,
          "apparentTemperature": 67.97,
          "dewPoint": 59.29,
          "humidity": 0.94,
          "pressure": 972.9,
          "windSpeed": 11.38,
          "windGust": 14.94,
          "windBearing": 173.66,
          "cloudCover": 1,
          "uvIndex": 0,
          "visibility": 1.55,
          "ozone": 315.51
        },
        {
          "time": 1683194400,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0066,
          "precipProbability": 0.24,
          "precipIntensityError": 0.0089,
          "precipAccumulation": 0.0066,
          "precipType": "rain",
          "temperature": 60.87,
          "apparentTemperature": 67.64,
          "dewPoint": 58.39,
          "humidity": 0.88,
          "pressure": 972.1,
          "windSpeed": 11.61,
          "windGust": 18.85,
          "windBearing": 161.78,
          "cloudCover": 1,
          "uvIndex": 0,
          "visibility": 3.29,
          "ozone": 315.98
        },
        {
          "time": 1683198000,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0064,
          "precipProbability": 0.31,
          "precipIntensityError": 0.0075,
          "precipAccumulation": 0.0064,
          "precipType": "rain",
          "temperature": 60.53,
          "apparentTemperature": 66.63,
          "dewPoint": 57.27,
          "humidity": 0.82,
          "pressure": 969.3,
          "windSpeed": 7.21,
          "windGust": 17.59,
          "windBearing": 137.35,
          "cloudCover": 0.99,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 314.91
        },
        {
          "time": 1683201600,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0062,
          "precipProbability": 0.38,
          "precipIntensityError": 0.0061,
          "precipAccumulation": 0.0062,
          "precipType": "rain",
          "temperature": 59.29,
          "apparentTemperature": 65.86,
          "dewPoint": 58.06,
          "humidity": 0.91,
          "pressure": 970.8,
          "windSpeed": 4.15,
          "windGust": 12.85,
          "windBearing": 132.27,
          "cloudCover": 0.87,
          "uvIndex": 0,
          "visibility": 8.39,
          "ozone": 315.95
        },
        {
          "time": 1683205200,
          "icon": "partly-cloudy-day",
          "summary": "Partly Cloudy",
          "precipIntensity": 0.0059,
          "precipProbability": 0.31,
          "precipIntensityError": 0.007,
          "precipAccumulation": 0.0059,
          "precipType": "rain",
          "temperature": 61.32,
          "apparentTemperature": 67.95,
          "dewPoint": 58.17,
          "humidity": 0.88,
          "pressure": 970.7,
          "windSpeed": 8.91,
          "windGust": 23.46,
          "windBearing": 166.4,
          "cloudCover": 0.44,
          "uvIndex": 0.53,
          "visibility": 9.38,
          "ozone": 315.91
        },
        {
          "time": 1683208800,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0056,
          "precipProbability": 0.24,
          "precipIntensityError": 0.0078,
          "precipAccumulation": 0.0056,
          "precipType": "rain",
          "temperature": 64.13,
          "apparentTemperature": 71.25,
          "dewPoint": 58.96,
          "humidity": 0.83,
          "pressure": 970.5,
          "windSpeed": 9.8,
          "windGust": 21.92,
          "windBearing": 184.09,
          "cloudCover": 1,
          "uvIndex": 1.72,
          "visibility": 10,
          "ozone": 317.1
        },
        {
          "time": 1683212400,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0053,
          "precipProbability": 0.16,
          "precipIntensityError": 0.0087,
          "precipAccumulation": 0.0053,
          "precipType": "rain",
          "temperature": 65.37,
          "apparentTemperature": 73.49,
          "dewPoint": 60.53,
          "humidity": 0.82,
          "pressure": 970.3,
          "windSpeed": 10.47,
          "windGust": 23.74,
          "windBearing": 193.11,
          "cloudCover": 1,
          "uvIndex": 3.19,
          "visibility": 10,
          "ozone": 317.85
        },
        {
          "time": 1683216000,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0058,
          "precipProbability": 0.22,
          "precipIntensityError": 0.0079,
          "precipAccumulation": 0.0058,
          "precipType": "rain",
          "temperature": 67.17,
          "apparentTemperature": 76.19,
          "dewPoint": 61.88,
          "humidity": 0.83,
          "pressure": 970.7,
          "windSpeed": 10.51,
          "windGust": 23.74,
          "windBearing": 196.99,
          "cloudCover": 1,
          "uvIndex": 4.69,
          "visibility": 10,
          "ozone": 319.82
        },
        {
          "time": 1683219600,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0063,
          "precipProbability": 0.28,
          "precipIntensityError": 0.0072,
          "precipAccumulation": 0.0063,
          "precipType": "rain",
          "temperature": 66.83,
          "apparentTemperature": 76.71,
          "dewPoint": 63.12,
          "humidity": 0.85,
          "pressure": 970.7,
          "windSpeed": 7,
          "windGust": 20.94,
          "windBearing": 184.57,
          "cloudCover": 1,
          "uvIndex": 6.12,
          "visibility": 10,
          "ozone": 319.32
        },
        {
          "time": 1683223200,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0068,
          "precipProbability": 0.34,
          "precipIntensityError": 0.0065,
          "precipAccumulation": 0.0068,
          "precipType": "rain",
          "temperature": 70.54,
          "apparentTemperature": 82.25,
          "dewPoint": 65.59,
          "humidity": 0.81,
          "pressure": 970.2,
          "windSpeed": 7.08,
          "windGust": 19.13,
          "windBearing": 194.86,
          "cloudCover": 1,
          "uvIndex": 5.31,
          "visibility": 10,
          "ozone": 322.4
        },
        {
          "time": 1683226800,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0093,
          "precipProbability": 0.33,
          "precipIntensityError": 0.0124,
          "precipAccumulation": 0.0093,
          "precipType": "rain",
          "temperature": 74.14,
          "apparentTemperature": 87.09,
          "dewPoint": 67.17,
          "humidity": 0.76,
          "pressure": 969.5,
          "windSpeed": 8.12,
          "windGust": 15.22,
          "windBearing": 199.06,
          "cloudCover": 1,
          "uvIndex": 3.72,
          "visibility": 10,
          "ozone": 323.96
        },
        {
          "time": 1683230400,
          "icon": "rain",
          "summary": "Rain",
          "precipIntensity": 0.0118,
          "precipProbability": 0.31,
          "precipIntensityError": 0.0184,
          "precipAccumulation": 0.0118,
          "precipType": "rain",
          "temperature": 72.91,
          "apparentTemperature": 85.85,
          "dewPoint": 67.17,
          "humidity": 0.82,
          "pressure": 968.5,
          "windSpeed": 5.01,
          "windGust": 10.33,
          "windBearing": 157.01,
          "cloudCover": 1,
          "uvIndex": 2.71,
          "visibility": 10,
          "ozone": 323.17
        },
        {
          "time": 1683234000,
          "icon": "cloudy",
          "summary": "Cloudy",
          "precipIntensity": 0.0143,
          "precipProbability": 0.29,
          "precipIntensityError": 0.0244,
          "precipAccumulation": 0.0143,
          "precipType": "rain",
          "temperature": 73.47,
          "apparentTemperature": 86.51,
          "dewPoint": 67.28,
          "humidity": 0.82,
          "pressure": 967.8,
          "windSpeed": 9.3,
          "windGust": 16.76,
          "windBearing": 147.26,
          "cloudCover": 1,
          "uvIndex": 1.57,
          "visibility": 10,
          "ozone": 323.24
        },
        {
          "time": 1683237600,
          "icon": "rain",
          "summary": "Rain",
          "precipIntensity": 0.0225,
          "precipProbability": 0.43,
          "precipIntensityError": 0.0317,
          "precipAccumulation": 0.0225,
          "precipType": "rain",
          "temperature": 74.82,
          "apparentTemperature": 89.07,
          "dewPoint": 68.74,
          "humidity": 0.82,
          "pressure": 967.6,
          "windSpeed": 10.68,
          "windGust": 18.29,
          "windBearing": 152.76,
          "cloudCover": 1,
          "uvIndex": 4.13,
          "visibility": 10,
          "ozone": 322.35
        },
        {
          "time": 1683241200,
          "icon": "rain",
          "summary": "Rain",
          "precipIntensity": 0.0307,
          "precipProbability": 0.56,
          "precipIntensityError": 0.0391,
          "precipAccumulation": 0.0307,
          "precipType": "rain",
          "temperature": 72.68,
          "apparentTemperature": 86.18,
          "dewPoint": 67.84,
          "humidity": 0.82,
          "pressure": 966.9,
          "windSpeed": 10.17,
          "windGust": 23.74,
          "windBearing": 136.67,
          "cloudCover": 1,
          "uvIndex": 3.02,
          "visibility": 10,
          "ozone": 320.69
        },
        {
          "time": 1683244800,
          "icon": "rain",
          "summary": "Rain",
          "precipIntensity": 0.0389,
          "precipProbability": 0.7,
          "precipIntensityError": 0.0465,
          "precipAccumulation": 0.0389,
          "precipType": "rain",
          "temperature": 67.22,
          "apparentTemperature": 77.77,
          "dewPoint": 64.05,
          "humidity": 0.9,
          "pressure": 964.19,
          "windSpeed": 19.2,
          "windGust": 31.04,
          "windBearing": 154.86,
          "cloudCover": 0.76,
          "uvIndex": 0.62,
          "visibility": 9.32,
          "ozone": 322.22
        },
        {
          "time": 1683248400,
          "icon": "rain",
          "summary": "Rain",
          "precipIntensity": 0.0309,
          "precipProbability": 0.54,
          "precipIntensityError": 0.0413,
          "precipAccumulation": 0.0309,
          "precipType": "rain",
          "temperature": 66.71,
          "apparentTemperature": 76.52,
          "dewPoint": 63.01,
          "humidity": 0.88,
          "pressure": 963.56,
          "windSpeed": 21.57,
          "windGust": 33.52,
          "windBearing": 147.75,
          "cloudCover": 0.16,
          "uvIndex": 0.43,
          "visibility": 10,
          "ozone": 323.17
        },
        {
          "time": 1683252000,
          "icon": "rain",
          "summary": "Rain",
          "precipIntensity": 0.0229,
          "precipProbability": 0.39,
          "precipIntensityError": 0.0361,
          "precipAccumulation": 0.0229,
          "precipType": "rain",
          "temperature": 65.25,
          "apparentTemperature": 74.74,
          "dewPoint": 62.56,
          "humidity": 0.91,
          "pressure": 963.38,
          "windSpeed": 18.59,
          "windGust": 34.91,
          "windBearing": 150.43,
          "cloudCover": 0,
          "uvIndex": 0,
          "visibility": 10,
          "ozone": 321.7
        }
      ]
    },
    "flags": {
      "sources": [
        "ETOPO1",
        "gfs",
        "gefs",
        "hrrrsubh",
        "hrrr"
      ],
      "sourceTimes": {
        "hrrr_0-18": "2023-05-03 01:00:00",
        "hrrr_subh": "2023-05-03 01:00:00",
        "hrrr_18-48": "2023-05-03 00:00:00",
        "gfs": "2023-05-02 18:00:00",
        "gefs": "2023-05-02 18:00:00"
      },
      "nearest-station": 0,
      "units": "us",
      "version": "V1.4.1"
    }
  }
}
